# -*- coding: utf-8 -*-
"""Alana Souza - 202_Est_Repeticao_EXTRA_M.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10vHotIjgFN_7rU554P2KwoAzy_-wiPQ5

### **LISTA DE EXERCÍCIOS EXTRA DE ESTRUTURA DE REPETIÇÃO PARA ESTUDOS**

###1. Construir um algoritmo para calcular a média aritmética de um conjunto de valores inteiros positivos. Digitar zero para sair.
"""

numero = int (input('Digite um valor numerico - 0 para sair '))
soma_valores = 0
while numero > 0:
  soma_valores = soma_valores + numero
  numero = int (input('Digite um valor numerico - 0 para sair '))
print('O valor acumulado é', soma_valores)

"""###2. Faça um programa que receba um conjunto de valores inteiros, calcule e exiba o maior e o menor valor do conjunto.


*   Para encerrar a entrada de dados, deve ser digitado o valor zero;
*   Para valores negativos, deve ser enviada uma mensagem;
*   Esses valores (zero e negativos) não entrarão nos cálculos.


"""

num = int (input('Digite um numero: '))
maior = num
menor = num
cc = str(input('Deseja continuar? S - Sim / N - Não  ')).upper()
while cc not in 'N':
    num = int(input('Digite um numero: '))
    if num > maior:
        maior = num
    if maior < menor:
        menor = num
    cc = str(input('Deseja continuar? S - Sim / N - Não  ')).upper()
print('O MAIOR número digitado foi {}.'.format(maior))
print('O MENOR número digitado foi {}.'.format(menor))

"""###3. Faça um programa que receba a idade e a altura de várias pessoas. Calcule e exiba a média das alturas das pessoas com mais de 20 anos. Para encerrar a entrada de dados, digite uma idade negativa ou igual a zero.



"""

idade = 1

soma_altura = 0

cont = 0

while idade > 0:   

    idade = int(input('Informe uma idade - 0 ou idade negativa para sair: ')) 

    if idade > 0:

        altura = float(input('Informe a altura: '))

        if idade > 20:

            soma_altura = soma_altura + altura

            cont += 1

media_altura = soma_altura / cont

print ('A média de altura das pessoas com mais de 20 anos é: ', media_altura)

"""###4. No final do ano muitas pessoas compram presentes. Faça um programa que registre as pessoas, usando como critério de parada a letra ‘n’, para a pergunta “Deseja cadastrar outro (‘s’/’n’)?”, para identificar o perfil dos compradores numa loja de roupas e apresente como resultado a:
*   Quantidade de mulheres e de homens;
*   Quantidade de mulheres e de homens abaixo e acima de 18 anos;
*   Quantidade de mulheres e de homens acima de 60 anos.
"""

sexoMasculino = 0
sexoFeminino = 0
mMenor18 = 0
fMenor18 = 0
mMaior18 = 0
fMaior18 = 0
mMais60 = 0
fMais60 = 0
opcao = input('Deseja cadastrar outro (s/n)?  ')
while opcao == 's':
  sexo = input('Informe o sexo (m/f)? ')
  idade = int (input('Informe a idade '))
  opcao = input('Deseja cadastrar outro (s/n)?  ')
  if sexo == 'm':
    sexoMasculino = sexoMasculino + 1
  if idade < 18:
    mMenor18 = mMenor18 + 1
  if idade > 18 and idade < 60:
    mMaior18 = mMaior18 + 1
  if idade > 60:
    mMais60 = mMais60 + 1
  if sexo == 'f':
    sexoFeminino = sexoFeminino + 1
  if idade <18:
    fMenor18 = fMenor18 + 1
  if idade > 18 and idade < 60:
    fMaior18 = fMaior18 + 1
  if idade > 60:
    fMais60 = fMais60 + 1
print('Quantidade de pessoas com sexo masculino:',sexoMasculino)
print('Quantidade de pessoas com sexo feminino',sexoFeminino)
print('Quantidade de mulheres maiores de 18 anos',fMaior18)
print('Quantidade de mulheres menores de 18 anos',fMenor18)
print('Quantidade de homens maiores de 18 anos',mMaior18)
print('Quantidade de homens menores de 18 anos',mMenor18)
print('Quantidade de homens maiores de 60 anos',mMais60)
print('Quantidade de mulheres maiores de 60 anos',fMais60)

"""###5. Faça um programa que leia cinco pares de valores (A,B), todos inteiros e positivos, um de cada vez. Mostre os números inteiros pares de A até B (inclusive). Considere que sempre os valores de A, serão menores que B, caso contrário, faça a variável A receber o valor de B. **Este algoritmo utiliza DUAS estruturas de repetição.**


"""

for x in range(1,3):
    a = int(input('Digite um valor positivo A: '))
    b = int(input('Digite um valor positivo B: '))
    if a > b:
        aux = a
        a = b
        b = aux
    for a1 in range(a,b + 1):
        if a1 % 2 == 0:
            print('par',a1)
        else:
            print('ímpar',a1)

"""###6. Faça um programa para o curso de ADS (6 módulos) que calcule e apresente os seguintes itens:
*  Quantidade de homens e mulheres de cada módulo;
*  Média de idades de cada módulo;
*  Quantidade de homens e mulheres do curso todo;
*  Média de idades do curso todo.

**Este algoritmo utiliza DUAS estruturas de repetição.**
"""

for modulo in range (1,7):
    print('Módulo',modulo,'.............................................................')    
    quantidadeAlunoPorModulo = 0
    quantidadeAlunoPorModuloF = 0
    somaidadeF = 0
    somaidade = 0
    idade = int (input('Informe a idade: '))
    while idade > 0:
        sexo = (input('Informe o sexo (m/f)? '))
        if sexo == 'm':
            quantidadeAlunoPorModulo = quantidadeAlunoPorModulo + 1
            somaidade = idade + idade
        if sexo == 'f':
            quantidadeAlunoPorModuloF = quantidadeAlunoPorModuloF + 1
        somaidadeF = somaidadeF + idade
        idade = int (input('Informe a idade: '))
    mediaAluno = somaidadeF / (quantidadeAlunoPorModulo + quantidadeAlunoPorModuloF)
    mediaIdade = (somaidade + somaidadeF) / 6
    print("Quantidade de aluno homens por modulo é de ",quantidadeAlunoPorModulo)
    print("Quantidade de aluno mulheres por modulo é de ",quantidadeAlunoPorModuloF)
print('A media das idades é de',mediaIdade)
print('A media de alunos é de',mediaAluno)