# -*- coding: utf-8 -*-
"""Alana Souza - 20202_P1_Alg_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S7Zko6zbcpgkD8-311T3C4vXeMC5odWh

#**P1 - Algoritmo - Início 9:30 - Término 11:05**. As 11:10 iniciaremos novo assunto.
###Dúvidas, escreva no **chat PRIVADO**

###[2,50 pontos] **1.** Utilize a linguagem de programação PYTHON. Crie um programa que leia o ano de nascimento de uma pessoa e o ano atual, calcule e mostre a idade da pessoa em:
a) anos

b) meses

c) dias
"""

anoAtual = int (input("Digite o ano atual "))
anoNasc = int (input("Digite o ano nascimento "))
idade = anoAtual - anoNasc
mes = idade * 12
dia = idade * 365
print("\n Você tem",idade,"anos","\n",mes,"meses",dia,"dias")

"""###[4,50 pontos] **2.** Utilize a linguagem de programação PYTHON. Crie um programa que leia o salário de um funcionário. Calcule e apresente os seguintes itens:
a) Valor descontado do INSS-Instituto Nacional do Seguro Social

b) Valor descontado do IR-Imposto de Renda

c) Valor do salário líquido

SALÁRIO R$ |  Alíquota INSS % |
 ---|---
até 1045.00  |	7.50  |
de 1045.01 até 2089.60	| 9.00 |
de 2089.61 até 3134.40	| 12.00 |
de 3134.41 até 6101.06  | 14.00|
Acima 6101.07 | R\$ 713.10|

O valor R$ 713.10 é fixo para qualquer valor de salário acima de R\$ 6101.07, conhecido como teto do INSS.

Base de cálculo	 R$ |  Alíquota IR % | Parcela a deduzir do IRPF R\$|
 ---|---|---
até 1903.98  |	0.00  | -
de 1903.99 até 2826.65	| 7.50  | 142.80
de 2826.66 até 3751.05	| 15.00 | 354.80
de 3751.06 até 4664.68  | 22.50 | 631.13
Acima  4664.68 | 27.50| 869.36

Exemplo: 

    salário: 3000.00 - 12%
    inss = 360.00
    Salário descontado do INSS 2640.00 * 7.50
    ir -> 198.00 - 142.80 = 55.20
    Salário líquido = 2584.80
"""

salario = float (input('Digite o seu salário: '))
if salario <=1045:
  inss = salario * (7.5 / 100)
  print('O salario descontado do INSS-Instituto Nacional do Seguro Social é de', inss, "R$")
elif salario >= 1045.01 and salario <= 2089.60:
  inss = salario * (9 / 100)
  print('O salario descontado do INSS-Instituto Nacional do Seguro Social é de', inss, "R$")
elif salario >= 2089.61 and salario <= 3134.40:
  inss = salario * (12 / 100)
  print('O salario descontado do INSS-Instituto Nacional do Seguro Social é de', inss, "R$")
elif salario  >= 3134.41 and salario <= 6101.06:
  inss = salario * (14 / 100)
  print('O salario descontado do INSS-Instituto Nacional do Seguro Social é de', inss, "R$")
else:
  salario >= 6101.07
  desconto = salario - 713.10
  print('O salario descontado do INSS-Instituto Nacional do Seguro Social é de', desconto, "R$")
if salario <= 1903.98:
  aliquota = inss - 0
  print('O salario descontado do IR-Imposto de Renda é de', aliquota, "R$")
elif salario >= 1903.99 and salario <= 2826.65:
  aliquota = inss - 142.80
  print('O salario descontado do IR-Imposto de Renda é de', aliquota, "R$")
elif salario >= 2826.66 and salario <= 3751.05:
  aliquota = inss - 354.80
  print('O salario descontado do IR-Imposto de Renda é de', aliquota, "R$")
elif salario  >= 3751.06 and salario <= 4664.68:
  aliquota = inss - 631.13
  print('O salario descontado do IR-Imposto de Renda é de', aliquota, "R$")
else:
  salario >= 4664.68
  aliquota = inss - 869.36
  print('O salario descontado do IR-Imposto de Renda é de', aliquota,"R$")
salarioLiquido = salario - inss - aliquota
print('O salario liquido é de',salarioLiquido, "R$")