# -*- coding: utf-8 -*-
"""Alana Souza - 20202_Alg_Manha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15970bYclPqAtW9MxYJuzcR-TYgSyDkrE

# Exercícios para construir programas com ENTRADA, PROCESSAMENTO e SAÍDA

### 1. Faça um programa que leia um número, multiplique ele por 2 e apresente o resultado.
      LEIA numero
      resultado = numero * 2
      ESCREVA resultado
"""

numero = float (input( 'Informe um valor a ser multiplicado por 4: '  ))
resultado = numero * 2
print('O seu resultado é', resultado)

"""### 2. Faça um programa que:
* receba quatro números inteiros
* calcule e mostre a soma desses números.

    LEIA n1, n2, n3, n4
    
    soma = n1 + n2 + n3 + n4
  
    ESCREVA soma

"""

n1 = int (input('Insira o primeiro numero inteiro: '))
n2 = int (input('Insira o segundo numero inteiro: '))
n3 = int (input('Insira o terceiro numero inteiro:  '))
n4 = int (input('Insira o quarto numero inteiro:  '))
soma = n1 + n2 + n3 + n4
print ('O resultado da soma destes numeros foram:', soma)

"""### 3. Faça um programa que receba três notas, calcule e mostre a média aritmética.
      LEIA nota1, nota2, nota3
      media = (nota1 + nota2 + nota3) / 3
      ESCREVA media
      
"""

nota1 = float (input('Insira sua primeira nota  '))
nota2 = float (input('Insira sua segunda nota '))
nota3 = float (input('Insira sua terceira nota  '))
media = (nota1 + nota2 + nota3) / 3
print ('A sua media é ', media, 'pontos')

"""### 4. Faça um programa que:
* receba o salário de um funcionário
* calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%.

      LEIA salario
      novoSalario = salario + (salario * 25 / 100)
      ESCREVA novoSalario
"""

salario = float (input('Insira o valor do seu salario '))
novoSalario = salario + (salario * 25 / 100)
print ('Seu novo salario é ', novoSalario,'R$')

"""### 5. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário.

      LEIA salario, percentual
      aumento = salario * percentual/100
      ESCREVA aumento
      novo_salario = salario + aumento
      ESCREVA novo_salario
"""

salario = float (input('Insira seu salario  '))
percentual = float (input('Insira o percentual de aumento '))
aumento = salario * percentual/100
print ('O percentual de aumento foi de ', aumento, '%')
novoSalario = salario + aumento
print ('Seu novo salario é', novoSalario, 'R$')

"""### 6. Faça um programa que receba o salário base de um funcionário, calcule e mostre o salário a receber, sabendo-se que o funcionário tem gratificação de 5% sobre o salário base e paga imposto de 7% também sobre o salário base.

    LEIA salario
    gratificacao = salario * 5 / 100
    imposto = salario * 7 / 100
    salario_a_receber = salario + gratificacao − imposto
    ESCREVA salario_a_receber
"""

salario = float (input('Digite seu salario  '))
gratificacao = salario * 5 / 100
imposto = salario * 7 / 100
salario_a_receber = salario + gratificacao - imposto
print ('Seu salario a receber é', salario_a_receber, 'R$')

"""### 7. Faça um programa que receba o salário base de um funcionário, calcule e mostre seu salário a receber, sabendo-se que o funcionário tem gratificação de 50,00 sobre o salário base e paga imposto que deve ser lido e é aplicado sobre o salário base.

    LEIA salario, perImposto
    imposto = salario * perImposto / 100
    salario_a_receber = salario + 50 - imposto
    ESCREVA salario_a_receber
"""

salario = float (input('Insira seu salario  '))
perImposto = float (input('Insira o seu percentual de imposto '))
imposto = salario * perImposto / 100
salario_a_receber = salario + 50 - imposto
print ('Seu salario a receber é', salario_a_receber, 'R$')

"""### 8. Faça um programa que receba o valor de um depósito e o valor da taxa de juros, calcule e mostre o valor do rendimento e o valor total depois do rendimento de um mês.

      LEIA deposito, taxa
      rendimento = deposito * taxa / 100
      total = deposito + rendimento
      ESCREVA rendimento
      ESCREVA total
"""

deposito = float (input('Digite seu valor de deposito '))
taxa = float (input('Digite o valor da taxa de juros  '))
rendimento = deposito * taxa / 100
total = deposito + rendimento
print ('O valor do seu rendimento é', rendimento,'R$  ' 'e o valor total de um mês é de', total,'R$')

"""### 9. Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: Área = (base * altura) / 2.

    LEIA base, altura
    area = (base * altura) / 2
    ESCREVA area
"""

base = float (input('Insira a base do triangulo  '))
altura = float (input('Insira a altura do triangulo  '))
area = (base * altura) / 2
print ('A area do triangulo é', area, 'm²')

"""### 10. Faça um programa que calcule e mostre a área de um círculo. Sabe-se que: Área = p * raio 2 (o número 2 significa potência, ou seja, raio é elevado ao quadrado)

    LEIA raio
    area = 3.1415 * raio ** 2
    ESCREVA area
"""

raio = float (input('Insira o raio  '))
area = 3.1415 * raio ** 2
print ('Sua area é', area, 'm²')

"""### 11. Faça um programa que receba um número positivo e maior que zero, calcule e mostre:
* O número digitado ao quadrado
* O número digitado ao cubo
* A raiz do número digitado
* A raiz cúbica do número digitao

      LEIA numero
      quadrado = numero ** 2
      cubo = numero ** 3
      raiz_quadrada = numero ** ½ (meio, ou 0.5)
      raiz_cubica = numero ** ⅓ (um terço, ou 0.33)
      ESCREVA quadrado, cubo, raiz_quadrada, raiz_cubica
"""

numero = float (input('Insira um numero positivo '))
quadrado = numero ** 2
cubo = numero ** 3
raizQuadrada = numero ** 0.5
raizCubica = numero ** 0.33
print ('\n O numero digitado ao quadrado é igual a', quadrado,'²', '\n O numero ao cubo é igual a', cubo, '\n A raiz quadrada é', raizQuadrada, '\n A raiz cubica é', raizCubica)

"""### 12. Faça um programa que receba dois números maiores que zero, calcule e mostre um elevado ao outro.

      LEIA numero1, numero2
      numero1_elevado_numero2 = numero1 ** numero2
      numero2_elevado_numero1 = numero2 ** numero1
      ESCREVA numero1_elevado_numero2, numero2_elevado_numero1
"""

numero1 = float (input('Insira um numero maior que zero '))
numero2 = float (input('Insira outro numero maior do que zero '))
numero1_elevado_numero2 = numero1 ** numero2
numero2_elevado_numero1 = numero2 ** numero1
print ('\n O primeiro numero elevado ao segundo é', numero1_elevado_numero2, '\n O segundo numero elevado ao primeiro é igual a', numero2_elevado_numero1)

"""### 13. Sabe-se que:

* pé = 12 polegadas
* 1 jarda = 3 pés
* 1 milha = 1,760 jarda

Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.

* Polegadas;
* Jardas;
* Milhas.

      LEIA pes
      polegadas = pes * 12
      jardas = pes / 3
      milhas = jardas / 1760
      ESCREVA polegadas, jardas, milhas
"""

pes = float (input('Insira um numero para ser convertido em pés '))
polegadas = pes * 12
jardas = pes / 3
milhas = jardas / 1760
print ('O numero em polegadas é igual a', polegadas, 'em jardas é igual a', jardas)
print ('E em milhas é igual a', milhas)

"""### 14. Faça um programa que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:
* a idade dessa pessoa;
* quantos anos ela terá em 2050.
      LEIA ano_atual
      LEIA ano_nascimento
      idade_atual = ano_atual − ano_nascimento
      idade_2050 = 2050 − ano_nascimento
      ESCREVA idade_atual

"""

anoAtual = int (input('Insira o ano atual: '))
anoNascimento = int (input('Insira sua data de nascimento:  '))
idadeAtual = anoAtual - anoNascimento
idade2050 = 2050 - anoNascimento
print (' \n Sua idade atual é', idadeAtual, 'anos',' \n Sua idade em 2050 será de', idade2050,'anos')

"""#### 15. O custo ao consumidor de um carro novo é a soma do preço de fábrica com o percentual de lucro do distribuidor e dos impostos aplicados ao preço de fábrica. Faça um programa que receba o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:
* o valor correspondente ao lucro do distribuidor;
* o valor correspondente aos impostos;
* o preço final do veículo.
        LEIA preco_fabrica
        LEIA percentual_lucro_distribuidr
        LEIA percentual_imposto
        lucro_distribuidor = preco_fabrica * percentual_lucro_distribuido / 100
        valor_imposto = preco_fabrica * percentual_imposto / 100
        preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
        ESCREVA lucro_distribuidor
        ESCREVA valor_imposto
        ESCREVA preco_final

"""

precoFabrica = float (input('Insira o valor de fabrica: '))
perLucro = float (input('Insira o percentual de lucro:  '))
perImposto = float (input('Insira o percentual de imposto:  '))
lucroDistribuidor = precoFabrica * perLucro / 100
valorImposto = precoFabrica * perImposto / 100
precoFinal = precoFabrica + lucroDistribuidor + valorImposto
print (' \n O valor de lucro do distribuidor é de', lucroDistribuidor, 'R$', ' \n O valor do imposto foi de', valorImposto, 'R$', ' \n O preço final foi de', precoFinal,'R$')

"""### 16. Faça um programa que receba o número de horas trabalhadas e o valor do salário mínimo, calcule e mostre o salário a receber, seguindo estas regras:
* a hora trabalhada vale a metade do salário mínimo.
* o salário bruto equivale ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
* o imposto equivale a 3% do salário bruto.
* o salário a receber equivale ao salário bruto menos o imposto.
      LEIA qtde_horas_trabalhadas
      LEIA valor_salario_minimo
      valor_hora_trabalhada = valor_salario_minimo / 2
      valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
      imposto = valor_salario_bruto * 3 / 100
      Valor_salario_liquido =  valor_salario_bruto - imposto
      ESCREVA valor_salario_liquido
"""

qtde_horas_trabalhadas = int (input('Insira a quantidade de horas trabalhadas:  '))
valor_salario_minimo = float (input('Insira o valor do salario minimo:  '))
valor_hora_trabalhada = valor_salario_minimo / 2
valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
imposto = valor_salario_bruto * 3 / 100
valor_salario_liquido = valor_salario_bruto - imposto
print ('O valor liquido do salario', valor_salario_liquido,'R$')

"""### 17. Um trabalhador recebeu seu salário e o depositou em sua conta bancária. Esse trabalhador emitiu dois cheques e agora deseja saber seu saldo atual. O banco criou uma taxa para a operação bancária de retirada que tem que pagar um imposto de 0.38% e o saldo inicial da conta está zerado.

      LEIA salario
      LEIA valor_cheque1
      LEIA valor_cheque2
      imposto_cheque1 = valor_cheque1 * 0.38 / 100
      saque1 = valor_cheque1 + imposto_cheque1
      imposto_cheque2 = cheque2 * 0.38 / 100
      saque2 = valor_cheque2 + imposto_cheque2
      saldo = salario - saque1 - saque2
      ESCREVA saldo

"""

salario = float (input('Insira o salario: '))
valor_cheque1 = float (input('Insira o valor do primeiro cheque '))
valor_cheque2 = float (input('Insira o valor do segundo cheque  '))
imposto_cheque1 = valor_cheque1 * 0.38 / 100
saque1 = valor_cheque1 + imposto_cheque1
imposto_cheque2 = valor_cheque2 * 0.38 / 100
saque2 = valor_cheque2 + imposto_cheque2
saldo = salario - saque1 - saque2
print ('Seu saldo é de ', saldo, 'R$')

"""### 18. Pedro comprou um saco de ração com peso em quilos. Ele possui dois gatos, para os quais fornece a quantidade de ração em gramas. A quantidade diária de ração fornecida para cada gato é sempre a mesma. Faça um programa que receba o peso do saco de ração em gramas e a quantidade de ração fornecida para cada gato, calcule e mostre quanto restará de ração no saco após cinco dias.

      LEIA peso_saco
      LEIA racao_gato1
      LEIA racao_gato2
      total_final = peso_saco − 5 * (racao_gato1 + racao_gato2)
      ESCREVA total_final
"""

peso_saco = int (input('Insira o peso do saco de ração em gramas  '))
racao_gato1 = int (input('Insira o numero em gramas da quantidade diaria de ração para o primeiro gato: '))
racao_gato2 = int (input('Insira o numero em gramas da quantidade diaria de ração para o segundo gato: '))
total_final = peso_saco - 5 * (racao_gato1 + racao_gato2)
print ('Após 5 dias restará ', total_final,'gramas')

"""### 19. Cada degrau de uma escada tem X de altura. Faça um programa que receba essa altura e a altura que o usuário deseja alcançar subindo a escada, calcule e mostre quantos degraus ele deverá subir para atingir seu objetivo, sem se preocupar com a altura do usuário. Todas as medidas fornecidas devem estar em metros.
      LEIA altura_degrau
      LEIA altura_desejada
      quantidade_de_degraus = altura_desejada // altura_degrau
      ESCREVA quantidade_de_degraus
**Observação**: o operador **//** em Python é utilizado para pegar a parte inteira de uma divisão
"""

altura_degrau = float (input('Insira a altura do degrau total em metros: '))
altura_desejada = float (input('Insira a altura desejada em metros: '))
quantidade_de_degraus = altura_desejada // altura_degrau
print ('A quantidade de degraus que você deverá subir é de', quantidade_de_degraus,'metros')

"""### 20. Faça um programa que receba a medida do ângulo (em graus) formado por uma escada apoiada no chão e encostada na parede e a altura da parede onde está a ponta da escada. Calcule e mostre a medida dessa escada. Observação: as funções trigonométricas implementadas nas linguagens de programação trabalham com medidas de ângulos em radianos.
      LEIA angulo
      LEIA altura
      radiano = angulo * 3.14 / 180
      escada = altura / seno(radiano)
      ESCREVA escada
**Observação**: Para usar seno em Python, deve-se usar esta linha de código **import math** e esta, no cálculo, **math.sin(numero)**

**import math**

escada = altura / **math.sin**(numero)
"""

angulo = int (input('Insira o ângulo em graus: '))
altura = float (input('Insira a altura: '))
radiano = angulo * 3.14 / 180
import math
escada = altura / math.sin(radiano)
print ('A medida da escada é de', escada,'radianos')

"""### 21. Uma pessoa deseja pregar um quadro em uma parede. Faça um programa para calcular e mostrar a que distância a escada deve estar da parede. A pessoa deve fornecer o tamanho da escada e a altura em que deseja pregar o quadro. Lembre-se de que o tamanho da escada deve ser maior que a altura que se deseja alcançar.
      LEIA Z
      LEIA X
      Y = Z ** 2 - X ** 2
      Y = Y **1/2
      ESCREVA Y

"""

z = float (input('Insira o tamanho da escada que seja maior do que a altura planejada:  '))
x = float (input('Insira a altura que deseja para pregar o quadro: '))
y = z ** 2 - x ** 2
y = y ** 1/2
print('A distancia da parede é de', y, 'metros')

"""###22. Sabe-se que o quilowatt de energia custa um quinto do salário mínimo. Faça um programa que receba o valor do salário mínimo e a quantidade de quilowatts consumida por uma residência. Calcule e mostre:


* o valor de cada quilowatt;
* o valor a ser pago por essa residência;
* o valor a ser pago com desconto de 15%.
      LEIA valor_salario
      LEIA qtde_quilowatt
      valor_quilowatt = valor_salario / 5
      valor_em_reais = valor_quilowatt * qtde_quilowatt
      valor_descontado = valor_em_reais * 15 / 100
      valor_com_desconto =  valor_em_reais − valor_descontado
      ESCREVA valor_quilowatt
      ESCREVA valor_em_reais
      ESCREVA valor_com_desconto

"""

valor_salario = float (input('Insira o valor do salario:  '))
qtde_quilowatt = float (input('Insira a quantidade em quilowatt:  '))
valor_quilowatt = valor_salario / 5
valor_em_reais = valor_quilowatt * qtde_quilowatt
valor_descontado = valor_em_reais * 15 / 100
valor_com_desconto = valor_em_reais - valor_descontado
print('\n O valor em quilowatt é de',valor_quilowatt,'Kw', '\n O valor em reais é de', valor_em_reais,'R$' '\n O valor com desconto é de', valor_com_desconto,'R$')

"""### 23. Faça um programa que receba um número real, encontre e mostre:

* a parte inteira desse número;
* a parte fracionária desse número;
* o arredondamento desse número.

      LEIA numero
      parte_inteira = numero // 1
      parte_fracionaria = numero - parte_inteira
      numero_arredondado = arredonda (numero)
      ESCREVA parte_inteira
      ESCREVA parte_fracionaria
      ESCREVA numero_arredondado
      
**Observação**: Para arredondar um número em Python, usa-se a função **round(numero)**, onde se o número real/float estiver em igual distância entre o inteiro de cima e o inteiro de baixo, esta função arredonda para o número par mais próximo.


"""

numero = float (input('Insira um numero real: '))
parte_inteira = numero // 1
parte_fracionaria = numero - parte_inteira
numero_arredondado = round(numero)
print ('\n A parte inteira deste numero é', parte_inteira, '\n O resultado da parte fracionaria é de', parte_fracionaria, '\n O numero arrendodado é igual a', numero_arredondado)

"""### 24. Faça um programa que receba uma hora formada por hora e minutos (um número real), calcule e mostre a hora digitada apenas em minutos. Lembre-se de que:
* para quatro e meia, deve-se digitar 4.30;
* os minutos vão de 0 a 59.
      LEIA hora
      h = pegar a parte inteira da variável hora
      minutos = hora − h
      conversao = (h * 60) + (minutos * 100)
      ESCREVA conversao

"""

hora = float (input('Informe um horario composto por horas e minutos: '))
h = hora // 1
minutos = hora - h
conversao = (h * 60) + (minutos * 100)
print ('O resultado é de ',conversao, 'minutos')

"""### 25. Faça um programa que receba o custo de um espetáculo teatral e o preço do convite desse espetáculo. Esse programa deverá calcular e mostrar a quantidade de convites que devem ser vendidos para que, pelo menos, o custo do espetáculo seja alcançado.

      LEIA custo
      LEIA convite
      quantidade = custo / convite
      ESCREVA quantidade

"""

custo = float (input('Insira o custo do espetaculo teatral: '))
convite = float (input('Insira o preço do convite:  '))
quantidade = custo / convite
print ('A quantidade necessaria de convites a serem vendidos para que o custo do espetaculo seja alcançado é de',quantidade,'convites')